name: 'PR Checks'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  get-terraform-directories-with-changes:
    name: Get Top Level Terraform Directories With Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Main
        run: git fetch origin main:refs/remotes/origin/main
      - name: Get All Top Level Directories Changed Under `terraform/`
        run: |
          NOTHING=""
          STARTS_WITH_TERRAFORM_DIRECTORY="^terraform/"
          EVERYTHING_AFTER_FIRST_FORWARD_SLASH="/(.*)"
          git diff origin/main --name-only -- terraform/         `# only compare files changed under the "terraform/" directory` \
            | sed 's/"$STARTS_WITH_TERRAFORM_DIRECTORY"/$NOTHING/' `# i.e. "terraform/front-end/main.tf" -> "front-end/main.tf"` \
            | sed -E 's/"$EVERYTHING_AFTER_FIRST_FORWARD_SLASH"/$NOTHING/'  `# i.e. "front-end/main.tf" -> "front-end"`
