name: 'PR Checks'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-changes:
    name: Terraform changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Main
        run: git fetch origin main:refs/remotes/origin/main
      - name: Get All Top Level Directories Changed Under `terraform/`
        run: |
          git diff origin/main --name-only -- terraform/        `# only compare files changed under the "terraform/" directory` \
            | sed 's/^terraform\///'                            `# removes "terraform/" at the start of the string i.e. "terraform/front-end/main.tf" -> "front-end/main.tf"` \
            | sed -E 's_/(.*)__'                                `# removes everything after the first "/" i.e. "front-end/main.tf" -> "front-end"`
