name: 'PR Checks'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-changes:
    name: Get All Top Level Directories Changed Under `terraform/`
    outputs:
      directories-matrix: ${{ steps.changed-terraform-directories.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin main:refs/remotes/origin/main
      - id: changed-terraform-directories
        run: |
          top_level_directories_changed=$(git diff origin/main --name-only -- terraform/   `# only compare files changed under the "terraform/" directory` \
            | sed 's/^terraform\///'                                                       `# removes "terraform/" at the start of the string i.e. "terraform/front-end/main.tf" -> "front-end/main.tf"` \
            | sed -E 's_/(.*)__'                                                           `# removes everything after the first "/" i.e. "front-end/main.tf" -> "front-end"` \
            | awk '{ printf("\"%s\",",$0) } END { print s }'                                `# converts multiline string to single line, wrapping each line contents with "", i.e. 'front-end\nbackend' -> '"front-end,"backend",'` \
          )
          echo $top_level_directories_changed
          
          output=$(echo "matrix={\"data\":[${top_level_directories_changed}]}")
          echo $output
          echo $output >> "$GITHUB_OUTPUT"

#      - id: set-matrix
#        run: |
#          echo ${{ steps.changed-terraform-directories }}
#          echo "matrix={\"data\":[\"aws-route53-example\",\"aws-s3-example\",]}" >> $GITHUB_OUTPUT

  display-output:
    name: Testing output
    needs: terraform-changes
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.terraform-changes.outputs.directories-matrix).data }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.directory }}
